### ISSUE TITLE
Incompatible with OS X

### ISSUE THREAD

**Issue by mjlangan** [narcello/findead#14]
The version of `grep` installed by default on OS X is BSD grep, not gnu grep, and does not support the `-P` flag used in the bash script. Mac users can install gnu grep using homebrew, but this installs it as `ggrep` and not just `grep`. If the script could detect the current OS and either use OS X-compatible commands (some examples at https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches) or rely on ggrep, that would make it work on OS X.

**Comment by narcello** [comment]
First, thanks for contribute :+1: 

I'll solve this issue and i'll let you know when it done.

**Comment by narcello** [comment]
First, thanks for contribute :+1: 

I'll work on this issue and i'll let you know about the progress.

**Comment by narcello** [comment]
@mjlanganI created PR #15 to solve this issue. I'll test today and if everthing is ok i'll merge PR and publish new version on npm. 

If you want/can test too in your machine, i'll be very gratefull  :smiley:

**Comment by narcello** [comment]
@mjlangan findead@0.0.3(beta version) is available for test osx compatibility :)
