### ISSUE TITLE
Create site gatsby ghpages

### ISSUE THREAD

**Issue by narcello** [narcello/findead#4]
Create site with gatsby and publish on ghpages

**Comment by brunoarueira** [comment]
@narcello Maybe vuepress is more appropriate, since it is a more lightweight and more doc friendly than gatsby. WDYT?

**Comment by narcello** [comment]
@brunoarueira  I'll checkout vuepress later, i'm focusing now in let package stable. But, between vue and react i'm prefer react cause i'm vue newbie.

**Comment by brunoarueira** [comment]
@narcello You don't have to touch any vue related thing, you'll work only with markdown if you want too! Check out here https://vuepress.vuejs.org/.

About WDYT, means "What do you think?" 😄

**Comment by narcello** [comment]
@brunoarueira lol now i understand... looks like easy and great :+1: 
'About WDYT, means "What do you think?"' I didn't knew kkkk nice :)
