### ISSUE TITLE
Not working with npx

### ISSUE THREAD

**Issue by AbdealiLoKo** [narcello/findead#68]
```
$ npx findead src
sh: 1: findead: not found
```

**Comment by narcello** [comment]
I'll be checking, thanks for open this issue :)

**Comment by narcello** [comment]
Hi. Can you try to use with this specific version: `1.2.2.`
`npx findead@1.2.2 <your arguments>`
I guess this new version 2.0.0-beta it's not working properly. :/

**Comment by mdornseif** [comment]
npx findead@1.2.2 src

works

**Comment by narcello** [comment]
@AbdealiLoKo @mdornseif 
Removed the wrong version, right now doesn't need to specify the version, just `npx findead src`
