### ISSUE TITLE
Command not found after installing 

### ISSUE THREAD

**Issue by comlaterra** [narcello/findead#74]
Does this package have any dependency?
It doesn't seem to work in my setup 🤷‍♂️
```
➜  npm install -g findead
added 1 package, and audited 2 packages in 661ms
found 0 vulnerabilities
➜  findead
zsh: command not found: findead
```

Thanks!

**Comment by narcello** [comment]
Hi. Can you try to install with this specific version: `1.2.2`. 
`npm i -g findead@1.2.2`
I guess this new version 2.0.0-beta it's not working properly.
